### ISSUE TITLE
加载后浏览器会报错 Error: Invalid value

### ISSUE THREAD

**Issue by leirock** [jiangtj-lab/hexo-cake-moon-menu#3]
使用该插件时候，浏览器会报错，如下截图：
![](https://user-images.githubusercontent.com/19180725/77507293-1a687780-6ea3-11ea-960d-ac8ad53d31f2.jpg)

开启PJAX后，每次点击新的页面会进一步报错如下：
![](https://user-images.githubusercontent.com/19180725/77507478-7df2a500-6ea3-11ea-88dc-f763ecbf042a.jpg)

**相关链接**

- [博客地址](https://blog.dlzhang.com)
- [源代码地址](https://github.com/lei2rock/blog)

**Comment by jiangtj** [comment]
![image](https://user-images.githubusercontent.com/15902347/77511785-c367a000-6eac-11ea-836a-d7a7ed368aef.png)
我这边没发现问题呀，你使用的是什么浏览器

**Comment by leirock** [comment]
对比了一下，macOS上Safari浏览器会有这样的保错，Chrome没有

**Comment by leirock** [comment]
补充一下，Safari上不能平滑地返回最顶部或者最下面，而是直接跳到最顶部或者最下面，手机和桌面端都是如此，Chrome就是平滑地返回最顶部或者最下面。不知道是不是与此有关。

**Comment by jiangtj** [comment]
> macOS上Safari浏览器

我在iPad上浏览你的网页显示是正常的，只是控制台报错么？

> 补充一下，Safari上不能平滑地返回最顶部或者最下面，而是直接跳到最顶部或者最下面，手机和桌面端都是如此，Chrome就是平滑地返回最顶部或者最下面。不知道是不是与此有关。

是的，有个平滑的属性，但是Safari不支持。。。

**Comment by leirock** [comment]
> > macOS上Safari浏览器
> 
> 我在iPad上浏览你的网页显示是正常的，只是控制台报错么？
> 
> > 补充一下，Safari上不能平滑地返回最顶部或者最下面，而是直接跳到最顶部或者最下面，手机和桌面端都是如此，Chrome就是平滑地返回最顶部或者最下面。不知道是不是与此有关。
> 
> 是的，有个平滑的属性，但是Safari不支持。。。

是的，除了平滑问题，使用起来都是正常的，只是控制台报错。

**Comment by jiangtj** [comment]
@lei2rock 能帮助测试下么，我没有mac

*注意：使用了fontawesome5的icon，所以next版本至少需要7.8*

**Comment by leirock** [comment]
> @lei2rock 能帮助测试下么，我没有mac
> 
> _注意：使用了fontawesome5的icon，所以next版本至少需要7.8_

我今天有空了测试一下吧～ 我在用 7.8 版本的

**Comment by jiangtj** [comment]
https://github.com/jiangtj-lab/hexo-cake-moon-menu/issues/6#issuecomment-619720990 fontawesome5的icon要到了7.9版本的NexT，mimi没合到7.8中，尴尬了，改早了

**Comment by leirock** [comment]
> [#6 (comment)](https://github.com/jiangtj-lab/hexo-cake-moon-menu/issues/6#issuecomment-619720990) fontawesome5的icon要到了7.9版本的NexT，mimi没合到7.8中，尴尬了，改早了

没事，我的next已经更新了fontawesome5，不过之前没空测试，等我测试没问题了尽快回复你哈～

**Comment by leirock** [comment]
新版经过测试， Safari 不会报错了（平滑返回最顶部问题依然存在，不过应该暂时无解）
