### ISSUE TITLE
Error：Uncaught SyntaxError: Identifier 'moonMenuListener' has already been declared

### ISSUE THREAD

**Issue by constown** [jiangtj-lab/hexo-cake-moon-menu#4]
Error：Uncaught SyntaxError: Identifier 'moonMenuListener' has already been declared

![image](https://user-images.githubusercontent.com/50108901/79677979-27218680-8229-11ea-84fd-fd058e6770f5.png)

使用谷歌浏览器，Hexo博客采用NexT主题，控制台一直报错。

**Comment by jiangtj** [comment]
done https://github.com/jiangtj-lab/hexo-cake-moon-menu/compare/v2.1.0...v2.1.2
