### ISSUE TITLE
图标无法显示

### ISSUE THREAD

**Issue by iwyang** [jiangtj-lab/hexo-cake-moon-menu#6]
![666](http://bore.vip/images/back2top.png)  图标不显示

**Comment by jiangtj** [comment]
你使用的是什么主题（版本号？）？

**Comment by iwyang** [comment]
NexT 7.8 _Gemini

**Comment by jiangtj** [comment]
呃，我看错next的新特性了，Font-Awesome 5 要到7.9才支持。。。

安装之前版本的插件把

```bash
npm i hexo-cake-moon-menu@2.1.2
# or yarn add hexo-cake-moon-menu@2.1.2
```

**Comment by luqicoder** [comment]
> 呃，我看错next的新特性了，Font-Awesome 5 要到7.9才支持。。。
> 
> 安装之前版本的插件把
> 
> ```shell
> npm i hexo-cake-moon-menu@2.1.2
> # or yarn add hexo-cake-moon-menu@2.1.2
> ```

我也是使用的NexT 7.8 _Gemini。参考安装2.1.2
出现了如下问题：评论框下面多了一部分，且样式不正常
![image](https://user-images.githubusercontent.com/49476849/110053967-3c49ca00-7d95-11eb-80b6-c754bdbafd18.png)

**Comment by jiangtj** [comment]
我测试了7.8，能正常使用，能提供demo么？

**Comment by luqicoder** [comment]
> 我测试了7.8，能正常使用，能提供demo么？

coder67.cn 你看一下

**Comment by jiangtj** [comment]
![image](https://user-images.githubusercontent.com/15902347/110055126-5ab0c500-7d97-11eb-8af0-8517a0814935.png)
也是正常的啊，可能浏览器缓存？:joy:

**Comment by luqicoder** [comment]
> ![image](https://user-images.githubusercontent.com/15902347/110055126-5ab0c500-7d97-11eb-8af0-8517a0814935.png)
> 也是正常的啊，可能浏览器缓存？😂
确实是浏览器缓存的原因
